---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: profiles
  namespace: gotk-system
spec:
  interval: 1m0s
  path: ./dev/profiles
  prune: true
  sourceRef:
    kind: GitRepository
    name: gotk-system

